### ISSUE TITLE
リポジトリ名をわかりやすいものに変更する

### ISSUE THREAD

**Issue by HosokawaR** [tsukuba-cojt/tsukuba-cojt.github.io#10]
現状の `.github` というリポジトリ名には以下ような問題点があると思います。

1. 直感的にどのようなリポジトリなのか分かりづらい
2. `.` が含まれるとやや扱いにくい
  clone 時にフォルダ名を変更すればよい話ですが、`.` が先頭に含まれると特に Windows では隠しフォルダになってしまいます

**Comment by Hidetaro7** [comment]
確かにあまり良くわかってなかった経緯があって

https://docs.github.com/ja/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile#adding-a-public-organization-profile-readme

これをやるのにサイト用のリポジトリにするのはあまり望ましくないかも、と、思った

**Comment by HosokawaR** [comment]
Organaization の `.github` リポジトリには特別な意味があったのですね。ありがとうございます。
活用すると面白そうな機能です。

> これをやるのにサイト用のリポジトリにするのはあまり望ましくないかも、と、思った

たしかにサイト用のリポジトリは別に`.github`リポジトリがあったほうがスッキリしそうです！

**Comment by takonasu** [comment]
`COJT_Portfolio`
とかですかね？

**Comment by knokmki612** [comment]
もし `https://tsukuba-cojt.github.io/` のurlでサイトをホスティングしたいのであれば、以下のようにする必要があると思いました

> リポジトリの名前と、任意で説明を入力してください。 ユーザもしくはOrganizationのサイトを作成しているなら、リポジトリは<user>.github.ioもしくは<organization>.github.ioという名前でなければなりません。

https://docs.github.com/ja/pages/getting-started-with-github-pages/creating-a-github-pages-site#:~:text=%E3%83%A6%E3%83%BC%E3%82%B6%E3%82%82%E3%81%97%E3%81%8F%E3%81%AFOrganization%E3%81%AE%E3%82%B5%E3%82%A4%E3%83%88%E3%82%92%E4%BD%9C%E6%88%90%E3%81%97%E3%81%A6%E3%81%84%E3%82%8B%E3%81%AA%E3%82%89%E3%80%81%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%81%AF%3Cuser%3E.github.io%E3%82%82%E3%81%97%E3%81%8F%E3%81%AF%3Corganization%3E.github.io%E3%81%A8%E3%81%84%E3%81%86%E5%90%8D%E5%89%8D%E3%81%A7%E3%81%AA%E3%81%91%E3%82%8C%E3%81%B0%E3%81%AA%E3%82%8A%E3%81%BE%E3%81%9B%E3%82%93%E3%80%82

**Comment by takonasu** [comment]
`https://tsukuba-cojt.github.io/` でホスティングするためそのように変更しました、ありがとうございます！
