### ISSUE TITLE
students_data.jsonの作成

### ISSUE THREAD

**Issue by Hidetaro7** [tsukuba-cojt/tsukuba-cojt.github.io#13]
@takonasu @nbz16 

学生データをjsonファイルにて作成お願いします。
またデータにこういった属性があったらいい、などアイデアがあれば別issueに上げてもらえたらと思います。

**Comment by Hidetaro7** [comment]
もしこちらが完了していたらissueをクローズしてください。 @takonasu @nbz16

**Comment by takonasu** [comment]
https://github.com/tsukuba-cojt/tsukuba-cojt.github.io/pull/15
にて解決
