### ISSUE TITLE
Wikiに使い方を記載する

### ISSUE THREAD

**Issue by Hidetaro7** [tsukuba-cojt/tsukuba-cojt.github.io#16]
学生が見てわかりやすいように、ガイドをしてあげてください。

**Comment by Hidetaro7** [comment]
各チームごとに代表者が

1. gitcloneする
2. `yarn install`して `yarn dev` コマンドで自分のマシンで立ち上げ
3. `git switch -c <任意のブランチ名>` で新しいブランチを作成する
4. `results` ディレクトリ内の `sample-team.md`を複製（ファイル名は任意）
5. チーム発表内容を記載する
6. pushする
7. 講師orTAからのApprovedを待つ
8. Approvedされたら自分自身でマージする、そうでなければコメントがあるので指示にしたがう
9. 修正があれば5.から行う

**Comment by Hidetaro7** [comment]
これをもとにWikiを記載してもらい、さらにレクチャー希望の人に向けて #21 を行う。

**Comment by nbz16** [comment]
作成してみたので確認お願いします．

**Comment by nbz16** [comment]
気になった点

- アイコン，カバー画像のサイズを指定した方がいいか
- Youtubeへの動画投稿の仕方もレクチャーした方がいいか

**Comment by Hidetaro7** [comment]
> アイコン，カバー画像のサイズを指定した方がいいか

したほうがいいいですね。

> Youtubeへの動画投稿の仕方もレクチャーした方がいいか

Youtubeに投稿ですか？ここは問題が多発しそうなときに考えたほうがよいと思うんですが、今はいいかなと思います。

**Comment by Hidetaro7** [comment]
あと、この分量であればREADME.mdに書くのが通例な気がしてきた。

**Comment by Hidetaro7** [comment]
やはりWikiのほうが分量的によい気がしてきたので、一旦完了とする。
