### ISSUE TITLE
2022-swのTeamの作成

### ISSUE THREAD

**Issue by Hidetaro7** [tsukuba-cojt/tsukuba-cojt.github.io#23]
https://github.com/orgs/tsukuba-cojt/teams/2022-sw

ここで一括で権限付与できるようになる。

- [ ] 全員をチームに入れることで完了とする

**Comment by Hidetaro7** [comment]
秋学期でよいので、ここのissueを完了させてほしい @takonasu @nbz16

**Comment by HosokawaR** [comment]
こちらの Issue 完了していそうな気がしますがどうでしょう？
@takonasu @nbz16

**Comment by takonasu** [comment]
誰がどのアカウントなのかわからない&秋学期になってからGitHubアカウントを作り直した人が何人かいることで，全員追加できているのかが不明です．
受講生から追加要請があった場合に随時追加するようにしているので，当issueはcloseしても良いかもしれません．
