### ISSUE TITLE
「単位計算ツール」から「授業単位計算ツール」に変更

### ISSUE THREAD

**Issue by Hidetaro7** [tsukuba-cojt/tsukuba-cojt.github.io#67]
タイムテーブルも変更が必要になりますので、別Issueを立てることで対応する。

_Originally posted by @Hidetaro7 in https://github.com/tsukuba-cojt/tsukuba-cojt.github.io/pull/66#pullrequestreview-1051844961_

**Comment by Hidetaro7** [comment]
タイムテーブルでは「Calculating Credits」となっているようですがこちらを「授業単位計算ツール」に変更してよいですか？ @yataro-fujinaga

**Comment by yataro-fujinaga** [comment]
@Hidetaro7 
はい
「授業単位計ツール」でお願いします

**Comment by Hidetaro7** [comment]
「授業単位計ツール」？？？
「授業単位計算ツール」とどっちが正しい？ @yataro-fujinaga

**Comment by yataro-fujinaga** [comment]
@Hidetaro7 
ミスタイプしてました

「授業単位計算ツール」
でお願いします、お手数おかけします
