### ISSUE TITLE
iframe で埋め込まれたスライドをレスポンシブ対応に

### ISSUE THREAD

**Issue by HosokawaR** [tsukuba-cojt/tsukuba-cojt.github.io#76]
普通に iframe で埋め込むとモバイル端末など画面サイズが小さい端末でははみ出してしまいます。

iframe を包み込む div などのいい感じにスタイルを定義してあげることで解決することができます。
各チームで使い回すならコンポーネント化してもいいかもしれません。

**Comment by Hidetaro7** [comment]
Google Slideで埋め込んだらこうなるのかな？
ドクセルだと勝手にレスポンシブになってくれる。
https://tsukuba-cojt.github.io/results/cc/

Youtubeと同じようにラッパーのdivにアスペクト比を固定することになるから、確実にどんな縦横比でもいい感じにするのはかなり面倒な感じがする（JSで無理やりとか、、できたらやりたくなくて）

#77 でもあったとおり、外部サービスに依存せず、PDFを埋め込む方法を共通のコンポーネント化するなど併せて考えたほうがいいかな

**Comment by Hidetaro7** [comment]
@HosokawaR CSSのラッパクラスだけ作って、はみ出したスライドのみ適用しました。
はみ出さないようにしているスライドのサービスもあるため、全ての適用するより、必要なスライドに対してのみ適用でもよいかと思いました。
