### ISSUE TITLE
録画された発表動画の埋め込み

### ISSUE THREAD

**Issue by Hidetaro7** [tsukuba-cojt/tsukuba-cojt.github.io#85]
これはTAさんにお願いしたいこと

成果発表の動画を、Youtubeにアップロード。
各チームごとの再生開始位置を指定した状態で各チームの発表ページ（markdownページ）に埋め込む。

なお、レスポンシブ対応にしたいので、iframeの親階層にdiv.youtubeをマークアップしてほしい。
（例）
https://github.com/tsukuba-cojt/tsukuba-cojt.github.io/blob/37c6ee2744f4a53786c5c3a2b0400e4ec91cd701/src/results/ar_team.md?plain=1#L46-L48

閲覧者がストレスなくその発表の動画をすぐに閲覧できるようにしたい。

- [ ] 各チームにYoutube動画が上記の仕様で埋め込まれたら完了

**Comment by takonasu** [comment]
Youtubeアップロードが今週中に終わるとのことなので、いったん動画を待ちます。
